"""Design-code provisions: parameter sets and clause references.

Two codes are supported:

* **Caltrans SDC 2.1 (January 2025)**
* **AASHTO Guide Specifications for LRFD Seismic Bridge Design, 3rd Ed. (2011)**

The seismic *methodology* is common to both documents — Mander confined
concrete, fibre moment-curvature with the Caltrans elasto-plastic (equal-area)
idealisation, the analytical plastic-hinge length, displacement-capacity from
the plastic mechanism, and the ESA displacement demand.  The items that *can*
differ between the two codes (the concrete shear model, longitudinal and
transverse reinforcement limits, displacement-ductility limits, the flexural
overstrength factor, the confinement coefficients, and the P-Delta / minimum-
strength factors) together with the clause references are collected here, so a
single code selection switches them consistently across the whole tool.

The one substantive numeric difference currently encoded is ``shear_model``:

* ``"caltrans"`` — SDC 2.0 §3.6.2, evaluated in psi, ``vc = F1·F2·√f'c`` with
  ``F2 ≤ 1.5`` and an overall cap of ``4√f'c``.
* ``"aashto"`` — SGS §8.6.2, evaluated in ksi, ``vc = 0.032·α'·(1 + Pu/2Ag)·√f'c``
  capped at ``min(0.11√f'c, 0.047α'√f'c)``, with ``fs = ρs·fyh ≤ 0.35 ksi`` and
  ``vc = 0`` when ``Pu`` is not compressive.  The 0.032 coefficient follows the
  **September 2024 errata** (LRFDSEIS-3-Errata, p. 8-10); the 3rd Ed. as printed
  shows 0.0032, which is a typographical error.

The two forms agree exactly where they overlap (α' = 3, no axial load); they
diverge in the caps, in the ``fs`` limit, and under net tension.

Two further differences are encoded:

* ``shaft_demand_factor`` — SGS §8.9 requires an oversized (Type II) shaft to
  reach **1.25×** the moment demand generated by the column overstrength hinge.
  The Caltrans entry is left at 1.0 pending verification of SDC 2.0 §7.7.3.5.
* ``detailing_checks`` / ``max_axial_coeff`` — SGS §8.8.6 (bar-diameter bond),
  §8.8.9 (max tie spacing, min tie size) and §8.7.2 (Pu ≤ 0.2·f'c·Ag).  These
  are ``False`` / ``None`` for Caltrans, meaning "equivalent not encoded", so
  the checks are skipped rather than guessed at.

The AASHTO SGS clause numbers and values below were verified page-by-page
against the 3rd edition (2023) plus its September 2024 errata.  Because every
code-specific value lives in this one module, any further confirmed difference
can be encoded here and will propagate everywhere.

This tool assumes **SDC D**: the in-hinge ``μΔ`` used by the shear model is the
displacement-ductility demand computed by the analysis (SGS §8.6.2 / Eq. 4.9-5),
not the fixed values SGS prescribes for SDC B (μΔ = 2) or SDC C (μΔ = 3).
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CodeProvisions:
    key: str
    name: str
    # ---- numeric limits / factors ----
    rho_l_min: float            # min longitudinal steel ratio
    rho_l_max: float            # max longitudinal steel ratio
    mu_d_limit_single: float    # displacement ductility demand limit, single column
    overstrength_factor: float  # Mo = factor * Mp (A706)
    conf_c1: float              # coeff on (Ag/Ac - 1) in rho_s,min (legacy/ACI)
    conf_c2: float              # coeff on f'c/fyh in rho_s,min (legacy/ACI)
    rho_s_min_floor: float      # constant floor on rho_s (e.g. AASHTO 0.005)
    # Minimum-transverse model: "aashto_floor" (max of ACI terms and the floor)
    # or "caltrans_table" (SDC 2.1 Table 5.3.8.2-1 lookup).
    transverse_min_model: str
    max_tie_spacing_model: str  # "aashto_8.8.9" | "caltrans_8.4.1" | ""
    axial_ratio_limit: float | None  # rho_dl = Pdl/(f'c*Ag) <= limit (SDC 5.3.3)
    vs_max_coeff: float         # max shear reinf: Vs <= coeff*sqrt(f'c)*Ae
    shear_model: str            # concrete shear model: "caltrans" | "aashto"
    shaft_demand_factor: float  # capacity-protection: Mne_shaft >= factor * Mo
    # Detailing checks (SGS 8.8.6 / 8.8.9) and the max-axial check (SGS 8.7.2).
    # ``None`` / ``False`` means "this code's equivalent has not been encoded",
    # and the corresponding check is skipped rather than guessed at.
    detailing_checks: bool
    max_axial_coeff: float | None   # Pu <= coeff * f'c * Ag
    # SGS 8.8.12: rho_s,shaft >= fraction * rho_s,column for oversized shafts.
    shaft_confinement_fraction: float | None
    fce_factor: float           # expected concrete strength f'ce = factor*f'c
    fce_floor: float | None     # lower bound on f'ce, ksi (Caltrans 3.3.6-4)
    min_shaft_oversize: float   # required D_shaft - D_col, in (Caltrans: 24)
    short_period_magnification: bool   # apply Rd (AASHTO SGS 4.3.3)
    pdelta_factor: float        # P*Delta <= factor * Mp
    min_strength_factor: float  # Vp >= factor * P_dead
    # ---- clause references ----
    ref_confined: str
    ref_flexure: str
    ref_plastic_hinge: str
    ref_displacement: str
    ref_demand: str
    ref_shear: str
    ref_overstrength: str
    ref_longitudinal: str
    ref_transverse: str
    ref_max_shear: str
    ref_ductility: str
    ref_pdelta: str
    ref_min_strength: str
    ref_shaft_capacity: str
    ref_detailing: str = ""
    ref_max_axial: str = ""


SDC_2_1 = CodeProvisions(
    key="SDC 2.1",
    name="Caltrans SDC 2.1 (January 2025)",
    rho_l_min=0.01, rho_l_max=0.04, mu_d_limit_single=5.0,
    overstrength_factor=1.2,
    # ACI confinement terms removed in SDC 2.0+; ρs,min now comes from Table
    # 5.3.8.2-1 via the "caltrans_table" model, so these are unused.
    conf_c1=0.0, conf_c2=0.0,
    rho_s_min_floor=0.0, vs_max_coeff=0.25, shear_model="caltrans",
    transverse_min_model="caltrans_table",    # SDC 2.1 Table 5.3.8.2-1
    max_tie_spacing_model="caltrans_8.4.1",    # min(6·dbl, 8 in)
    axial_ratio_limit=0.15,                    # §5.3.3-1 ρdl ≤ 0.15
    # §6.2.5.3: MD <= phi*Mne for a shaft cast in a dry/dewatered hole
    # (factor 1.0); MD <= 0.8*phi*Mne for the slurry-displacement method, i.e.
    # an effective 1.25.  Default is the dry-hole case; set 1.25 for slurry.
    # The commentary is explicit that 1.25 does NOT apply to shaft *shear*,
    # which the app already leaves unamplified.
    shaft_demand_factor=1.0,
    detailing_checks=True, max_axial_coeff=None,
    # No §8.8.12-style confinement-fraction rule for a Type II shaft in SDC 2.1:
    # §5.3.8.4 governs the *column* (table + outside-hinge 50%); the 75% rule
    # (§5.3.8.5) is for *Type I* shafts.  The Type II shaft is purely
    # shear-capacity-protected (§6.2.5.3), so no confinement fraction applies.
    shaft_confinement_fraction=None,
    fce_factor=1.3, fce_floor=5.0,      # §3.3.6 Table 3.3.6-1, Eq. 3.3.6-4
    min_shaft_oversize=24.0,            # §6.2.5.1 / Type II definition
    short_period_magnification=False,   # no Rd equivalent in Caltrans SDC
    pdelta_factor=0.25, min_strength_factor=0.10,
    ref_confined="Caltrans SDC 2.1 §3.3.6 (concrete) / §5.3.5; Mander et al. (1988)",
    ref_flexure="Caltrans SDC 2.1 §5.3.6.2 (moment-curvature)",
    ref_plastic_hinge="Caltrans SDC 2.1 §5.3.4 (equivalent plastic-hinge length)",
    ref_displacement="Caltrans SDC 2.1 §5.2 (global displacement capacity)",
    ref_demand="Caltrans SDC 2.1 §4.2.1 (Equivalent Static Analysis)",
    ref_shear="Caltrans SDC 2.1 §5.3.7.2 (concrete) & §5.3.7.3 (transverse)",
    ref_overstrength="Caltrans SDC 2.1 §4.4.2 (Mo = 1.2·Mp, A706)",
    ref_longitudinal="Caltrans SDC 2.1 §5.3.9 (0.01 ≤ ρl ≤ 0.04)",
    ref_transverse="Caltrans SDC 2.1 §5.3.8.2 Table 5.3.8.2-1 (min ρs); "
                   "§5.3.8.4 (Type II shafts)",
    ref_max_shear="Caltrans SDC 2.1 §5.3.7.4 (max shear reinf.: Vs ≤ 0.25√f'c·Ae)",
    ref_ductility="Caltrans SDC 2.1 §4.4.1 (μd ≤ 5, single-column bent)",
    ref_pdelta="Caltrans SDC 2.1 §4.4.4 (P-Δ: Pdl·Δr ≤ 0.25·Mp)",
    ref_min_strength="Caltrans SDC 2.1 §4.4 (minimum lateral strength)",
    ref_shaft_capacity="Caltrans SDC 2.1 §6.2.5.3 (Type II shaft: MD ≤ φMne, "
                       "or ≤ 0.8φMne slurry)",
    ref_detailing="Caltrans SDC 2.1 §8.4.1.1 (max tie spacing min(6·dbl, 8 in)) "
                  "& §8.4.2 (longitudinal lateral spacing)",
    ref_max_axial="Caltrans SDC 2.1 §5.3.3 (ρdl = Pdl/f'c·Ag ≤ 0.15)",
)

AASHTO_SGS_3 = CodeProvisions(
    key="AASHTO SGS 3rd Ed.",
    name="AASHTO Guide Spec. for LRFD Seismic Bridge Design, 3rd Ed. (2011)",
    rho_l_min=0.01, rho_l_max=0.04, mu_d_limit_single=5.0,
    overstrength_factor=1.2, conf_c1=0.0, conf_c2=0.0,
    rho_s_min_floor=0.005, vs_max_coeff=0.25, shear_model="aashto",
    transverse_min_model="aashto_floor",   # max(ACI terms, 0.005 floor) = 0.005
    max_tie_spacing_model="aashto_8.8.9",   # min(D/5, 6·dbl, 6 or 8 in)
    axial_ratio_limit=None,                 # SGS uses Pu ≤ 0.2·f'c·Ag (§8.7.2)
    shaft_demand_factor=1.25,       # §8.9, oversized (Type II) shafts
    detailing_checks=True, max_axial_coeff=0.2,
    shaft_confinement_fraction=0.5,   # §8.8.12
    fce_factor=1.3,                   # §8.4.4-1, f'ce >= 1.3 f'c
    fce_floor=None,                   # SGS sets no floor on f'ce
    min_shaft_oversize=0.0,           # "larger in diameter", Owner's discretion
    short_period_magnification=True,  # §4.3.3 Rd
    pdelta_factor=0.25, min_strength_factor=0.10,
    ref_confined="AASHTO SGS 3rd Ed. §8.4.4; Mander et al. (1988)",
    ref_flexure="AASHTO SGS 3rd Ed. §8.4 / §4.11.5 (moment-curvature)",
    ref_plastic_hinge="AASHTO SGS 3rd Ed. §4.11.6 (analytical plastic-hinge length)",
    ref_displacement="AASHTO SGS 3rd Ed. §4.8.1 (displacement capacity)",
    ref_demand="AASHTO SGS 3rd Ed. §4.3–4.4 (ESA / ESM)",
    ref_shear="AASHTO SGS 3rd Ed. §8.6.2 (concrete) & §8.6.3 (transverse), "
              "φs = 0.90 per §8.6.1",
    ref_overstrength="AASHTO SGS 3rd Ed. §8.5 (Mpo = λmo·Mp, λmo = 1.2 A706)",
    ref_longitudinal="AASHTO SGS 3rd Ed. §8.8.1 (0.01 ≤ ρl ≤ 0.04)",
    ref_transverse="AASHTO SGS 3rd Ed. §8.6.5 (ρs ≥ 0.005); confinement §8.8.2 separate",
    ref_max_shear="AASHTO SGS 3rd Ed. §8.6.4 (Vs ≤ 0.25√f'c·Ae)",
    ref_ductility="AASHTO SGS 3rd Ed. §4.9 (μD limits)",
    ref_pdelta="AASHTO SGS 3rd Ed. §4.11.5 (P-Δ: Pdl·Δr ≤ 0.25·Mp)",
    ref_min_strength="AASHTO SGS 3rd Ed. §8.7.1 (minimum lateral strength)",
    ref_shaft_capacity="AASHTO SGS 3rd Ed. §8.9 (oversized shafts: "
                       "Mne ≥ 1.25·Mpo)",
    ref_detailing="AASHTO SGS 3rd Ed. §8.8.6 (max bar diameter) & §8.8.9 "
                  "(max tie spacing, min tie size)",
    ref_max_axial="AASHTO SGS 3rd Ed. §8.7.2 (Pu ≤ 0.2·f'c·Ag)",
)

# Backwards-compatible alias: older code/tests referenced ``SDC_2_0``.
SDC_2_0 = SDC_2_1

PROVISIONS: dict[str, CodeProvisions] = {
    SDC_2_1.key: SDC_2_1,
    AASHTO_SGS_3.key: AASHTO_SGS_3,
}

# Older saved projects may carry the previous "SDC 2.0" key.
_KEY_ALIASES = {"SDC 2.0": "SDC 2.1"}


def get_provisions(key: str) -> CodeProvisions:
    """Return the provisions for ``key`` (defaults to Caltrans SDC 2.1)."""
    return PROVISIONS.get(_KEY_ALIASES.get(key, key), SDC_2_1)
